# nblite configuration
export_pipeline = """
nbs_nodes -> lib_nodes
nbs_nodes -> pts_nodes

nbs_annotation_nodes -> lib_annotation_nodes
nbs_annotation_nodes -> pts_annotation_nodes

nbs_scratch -> pts_scratch

nbs_validation -> lib_validation
nbs_validation -> pts_validation
"""

[fill]
code_locations = [
    "nbs_nodes",
    "nbs_annotation_nodes",
]
exclude_patterns = [
    "**/*_v1.ipynb",
]

[cl.nbs_nodes]
path = "nbs/ai_index/nodes"
format = "ipynb"

[cl.pts_nodes]
path = "pts/ai_index/nodes"
format = "percent"

[cl.lib_nodes]
path = "src/ai_index/nodes"
format = "module"


[cl.nbs_annotation_nodes]
path = "nbs/ai_annotations/nodes"
format = "ipynb"

[cl.pts_annotation_nodes]
path = "pts/ai_annotations/nodes"
format = "percent"

[cl.lib_annotation_nodes]
path = "src/ai_annotations/nodes"
format = "module"


[cl.nbs_scratch]
path = "nbs/scratch"
format = "ipynb"

[cl.pts_scratch]
path = "pts/scratch"
format = "percent"


[cl.nbs_validation]
path = "nbs/validation"
format = "ipynb"

[cl.pts_validation]
path = "pts/validation"
format = "percent"

[cl.lib_validation]
path = "src/validation"
format = "module"
