# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/isambard_utils/env.ipynb

__all__ = ['averify_runner_env']

# %% nbs/isambard_utils/env.ipynb 2
from .config import IsambardConfig
from .ssh import arun as async_ssh_run, _get_config, _run_sync

# %% nbs/isambard_utils/env.ipynb 3
def _shlex_quote(s: str) -> str:
    import shlex
    return shlex.quote(s)

# %% nbs/isambard_utils/env.ipynb 4
async def _aensure_uv(*, config: IsambardConfig) -> None:
    """Install uv on the remote if not already present (async)."""
    result = await async_ssh_run("bash -lc 'which uv'", config=config, check=False)
    if result.returncode == 0:
        return
    # Install uv using the official installer
    await async_ssh_run("curl -LsSf https://astral.sh/uv/install.sh | sh", config=config,
                        timeout=120)

# %% nbs/isambard_utils/env.ipynb 5
async def _aensure_venv(*, config: IsambardConfig, print_fn=print) -> None:
    """Create venv and sync dependencies if needed (async).

    Skips ``uv sync`` when the pyproject.toml hash matches the last
    successful sync (stored in ``.venv/.pyproject_hash``).  This avoids
    the very slow Lustre I/O on repeated runs with unchanged deps.
    On failure, retries once (Lustre rename failures are transient).
    """
    import subprocess

    # Fast path: skip sync if pyproject.toml + uv.lock haven't changed since last success
    check_script = f"""
cd {config.project_dir}
[ -f .venv/bin/python ] && [ -f .venv/.pyproject_hash ] && \
  [ "$(cat pyproject.toml uv.lock 2>/dev/null | sha256sum | cut -d' ' -f1)" = "$(cat .venv/.pyproject_hash)" ] && \
  echo DEPS_CURRENT || echo DEPS_STALE
""".strip()
    result = await async_ssh_run(
        f"bash -lc {_shlex_quote(check_script)}", config=config, check=False,
    )
    if result.returncode == 0 and "DEPS_CURRENT" in result.stdout:
        print_fn("runner setup: dependencies up to date")
        return

    # Slow path: run uv sync, save hash on success
    print_fn("runner setup: installing dependencies (uv sync)...")
    sync_script = f"""
set -e
cd {config.project_dir}
export UV_CACHE_DIR={config.project_dir}/.uv_cache
export UV_LINK_MODE=copy
uv sync --no-dev --no-install-project
cat pyproject.toml uv.lock 2>/dev/null | sha256sum | cut -d' ' -f1 > .venv/.pyproject_hash
""".strip()
    try:
        await async_ssh_run(
            f"bash -lc {_shlex_quote(sync_script)}", config=config, timeout=3600,
        )
    except subprocess.CalledProcessError:
        # Retry once for transient Lustre failures (rename ENOENT)
        print_fn("runner setup: uv sync failed, retrying...")
        await async_ssh_run(
            f"bash -lc {_shlex_quote(sync_script)}", config=config, timeout=3600,
        )

# %% nbs/isambard_utils/env.ipynb 6
async def _afix_lustre_hardlinks(*, config: IsambardConfig) -> None:
    """Reinstall packages that were installed with hardlinks on Lustre.

    uv defaults to hardlink mode, which causes stale inode issues on Lustre:
    compute nodes can see the file via ``ls`` but ``stat``/``open`` fail with
    ENOENT because the inode was replaced on the login node during a reinstall.

    This checks whether torch's init file has link count > 1 (indicating
    hardlinks) and, if so, reinstalls torch, triton and vllm with copy mode
    so every file gets its own inode. Idempotent: once packages are installed
    with copy mode (link count == 1), this is a no-op.
    """
    check_script = f"""
cd {config.project_dir}
site=$(.venv/bin/python -c "import site; print(site.getsitepackages()[0])")
torch_init="$site/torch/__init__.py"
[ -f "$torch_init" ] && stat -c %h "$torch_init" || echo 0
""".strip()
    result = await async_ssh_run(
        f"bash -lc {_shlex_quote(check_script)}", config=config, check=False,
    )
    if result.returncode != 0:
        return
    link_count = result.stdout.strip()
    if not link_count.isdigit() or int(link_count) <= 1:
        return  # Already using copies, nothing to do

    # Reinstall torch, triton, vllm with copy mode to eliminate hardlinks.
    # --no-deps on triton prevents uv from pulling CPU-only torch from PyPI.
    fix_script = f"""
cd {config.project_dir}
export UV_CACHE_DIR={config.project_dir}/.uv_cache
export UV_LINK_MODE=copy
uv pip install --reinstall-package torch --reinstall-package torchvision torch torchvision --index-url {config.torch_index_url} --quiet
uv pip install --reinstall-package triton --no-deps triton --quiet
""".strip()
    await async_ssh_run(
        f"bash -lc {_shlex_quote(fix_script)}", config=config, timeout=600,
    )

    # Reinstall vllm if present
    vllm_check = await async_ssh_run(
        f"bash -lc {_shlex_quote(f'cd {config.project_dir} && .venv/bin/python -c \"import vllm\"')}",
        config=config, check=False,
    )
    if vllm_check.returncode == 0:
        vllm_script = f"""
cd {config.project_dir}
export UV_CACHE_DIR={config.project_dir}/.uv_cache
export UV_LINK_MODE=copy
uv pip install --reinstall-package vllm vllm --extra-index-url {config.torch_index_url} --quiet
""".strip()
        await async_ssh_run(
            f"bash -lc {_shlex_quote(vllm_script)}", config=config, timeout=1200,
        )

# %% nbs/isambard_utils/env.ipynb 7
async def _aensure_cuda_torch(*, config: IsambardConfig) -> None:
    """Replace CPU-only torch with CUDA build if needed, pinned to lock versions.

    PyPI's default torch wheel is CPU-only on ARM64 (GH200), so we reinstall
    from the cu126 index. The version is pinned to whatever ``uv sync``
    resolved from the lockfile, because reinstalling without a version pin
    picks up the cu126 index's latest release — which has historically drifted
    away from vllm's compiled-against ABI (e.g. torch 2.12.0+cu126 breaking
    vllm 0.11.0's ``c10::cuda::c10_cuda_check_implementation`` symbol
    expectations).

    Similarly, vllm is reinstalled at the lock-pinned version so that the
    PyPI wheel selected matches the torch ABI we just installed.

    Idempotent: if torch's version string already contains ``+cu``, returns
    without changes.
    """
    import re

    # Check if torch already has CUDA support
    check_script = f"""
cd {config.project_dir}
.venv/bin/python -c "import torch; print(torch.__version__)"
""".strip()
    result = await async_ssh_run(
        f"bash -lc {_shlex_quote(check_script)}", config=config, check=False,
    )
    torch_version_full = result.stdout.strip() if result.returncode == 0 else ""
    if "+cu" in torch_version_full:
        return  # Already has working CUDA torch
    # torch is either missing, broken (import error), or CPU-only: reinstall

    # Capture the lock-resolved torch version so the cu126 reinstall doesn't
    # silently bump to a newer torch that is ABI-incompatible with vllm.
    m = re.match(r"^(\d+\.\d+\.\d+)", torch_version_full)
    if not m:
        raise RuntimeError(
            f"_aensure_cuda_torch: cannot parse torch version from "
            f"{torch_version_full!r}; expected something like '2.8.0'."
        )
    torch_version = m.group(1)

    # Check if vllm is installed (before changing torch) and capture its version
    vllm_check_script = f"""
cd {config.project_dir}
.venv/bin/python -c "import vllm; print(vllm.__version__)" 2>/dev/null || echo MISSING
""".strip()
    vllm_check = await async_ssh_run(
        f"bash -lc {_shlex_quote(vllm_check_script)}", config=config, check=False,
    )
    vllm_version_full = vllm_check.stdout.strip()
    vllm_version: str | None = None
    if vllm_version_full and vllm_version_full != "MISSING":
        m = re.match(r"^(\d+\.\d+\.\d+)", vllm_version_full)
        if m:
            vllm_version = m.group(1)

    # Reinstall CUDA torch pinned to the lock version.
    # UV_LINK_MODE=copy avoids hardlinks on Lustre, which can leave stale
    # inodes on compute nodes after reinstalls.
    install_script = f"""
cd {config.project_dir}
export UV_CACHE_DIR={config.project_dir}/.uv_cache
export UV_LINK_MODE=copy
uv pip install 'torch=={torch_version}' torchvision --index-url {config.torch_index_url} --reinstall-package torch --reinstall-package torchvision --quiet
""".strip()
    await async_ssh_run(
        f"bash -lc {_shlex_quote(install_script)}", config=config, timeout=600,
    )

    # Reinstall vllm pinned to its lock version so the wheel chosen from PyPI
    # is the one compiled against the torch ABI we just installed.
    if vllm_version is not None:
        vllm_script = f"""
cd {config.project_dir}
export UV_CACHE_DIR={config.project_dir}/.uv_cache
export UV_LINK_MODE=copy
uv pip install 'vllm=={vllm_version}' --extra-index-url {config.torch_index_url} --reinstall-package vllm --quiet
""".strip()
        await async_ssh_run(
            f"bash -lc {_shlex_quote(vllm_script)}", config=config, timeout=1200,
        )


# %% nbs/isambard_utils/env.ipynb 8
async def averify_runner_env(*, config: IsambardConfig, print_fn=print) -> None:
    """Fail-fast sanity check that torch and vllm import together cleanly.

    Runs ``import torch; import vllm`` in the project venv and asserts
    that torch has ``+cu`` in its version. If either import raises (e.g.
    a torch/vllm ABI mismatch, or a missing internal file from a partial
    Lustre write) this surfaces the error at runner-setup time — in the
    Hetzner bg-job.log within seconds — rather than waiting hours for a
    queued Slurm job to fail with the same error.

    Raises RuntimeError with the full python stderr on failure.
    """
    verify_script = f"""
cd {config.project_dir}
.venv/bin/python -c "
import sys
try:
    import torch
    import vllm
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(2)
assert '+cu' in torch.__version__, f'torch is not CUDA-enabled: {{torch.__version__}}'
print(f'OK torch={{torch.__version__}} vllm={{vllm.__version__}}')
"
""".strip()
    result = await async_ssh_run(
        f"bash -lc {_shlex_quote(verify_script)}", config=config, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Runner env sanity check failed (exit {result.returncode}).\n"
            f"This usually means a torch/vllm ABI mismatch or a corrupted\n"
            f"package on the Isambard venv. Inspect "
            f"{config.project_dir}/.venv/lib/python3.12/site-packages/ for\n"
            f"missing files (METADATA, *.so, version.py).\n"
            f"--- stdout ---\n{result.stdout}\n"
            f"--- stderr ---\n{result.stderr or '(empty)'}"
        )
    print_fn(f"runner setup: {result.stdout.strip()}")
